name: "Validate PR"

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
    branches:
      - main
      - 'release*/**'

jobs:
  lint-test:
    name: Lint & Test Code
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout the commit'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: 'Install and Prepare'
        shell: bash
        run: |
          pnpm --frozen-lockfile
          # pnpm build-types

      - name: ESLint
        shell: bash
        run: |
          pnpm lint

      - name: 'Unit Tests with Coverage'
        shell: bash
        run: |
          pnpm test-ci
